# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1295, 801)
        Form.setStyleSheet("background-color: rgb(224, 203, 197);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(590, 20, 101, 31))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 10pt \"Segoe UI Black\";")
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(10, 60, 1271, 731))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 151, 28))
        self.pushButton.setStyleSheet("background-color: rgb(161, 89, 38);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 8pt \"Segoe UI Black\";")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Coffee"))
        self.label.setText(_translate("Form", "Кофиёк :3"))
        self.pushButton.setText(_translate("Form", "Добавить/изменить"))
